# Generated by Django 4.0 on 2025-07-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='festivity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
