# Generated by Django 4.0 on 2025-07-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0007_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_img',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
